# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'githubRepo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for githubRepo
  pod 'OAuthSwift', '~> 2.0.0'

  target 'githubRepoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
